# Generated by Django 4.0.2 on 2022-05-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='location',
            field=models.CharField(choices=[('Andijon', 'Andijon'), ('Namangan', 'Namangan'), ('Samarqand', 'Samarqand'), ('Tashkent', 'Tashkent'), ('Jizzax', 'Jizzax'), ('Surxondaryo', 'Surxondaryo'), ('Navoiy', 'Navoiy'), ('Xorazm', 'Xorazm'), ('Qashqadaryo', 'Qashqadaryo'), ('Buxoro', 'Buxoro'), ('Sirdaryo', 'Sirdaryo'), ('Fargona', 'Fargona')], max_length=256, verbose_name='loacation'),
        ),
    ]
