# Generated by Django 4.0.2 on 2022-07-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_book_is_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_view',
            field=models.BooleanField(default='False'),
            preserve_default=False,
        ),
    ]
