# Generated by Django 4.0.6 on 2022-07-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_book_is_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='book_images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_view',
            field=models.BooleanField(default=False),
        ),
    ]
